name: adcp
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core
  - python=3.10
  - pip
  - setuptools
  - wheel

  # Scientific stack
  - numpy=1.23.5
  - pandas=2.2.3
  - scipy=1.9.3
  - matplotlib=3.9.2
  - xarray>=2023.5.0
  - netcdf4=1.7.2
  - bottleneck=1.5.0
  - dask=2024.5.0
  - click
  - requests
  - pyyaml
  - pip:
      - dolfyn==1.3.0
      - seawater==3.3.5
      - envass==1.0.0